Implement recv() and recvmsg()
enarx/cipherpipe pull request #10
Opened 2019-07-23 19:46 UTC by yingxiongraomingzk

Implement recv() and recvmsg() function. But tls part is not implemented
and needs to be done in the future.

2019-07-23 19:58 UTC, npmccallum requested changes

2019-07-23 19:58 UTC, npmccallum commented on src/lib.rs
> +}
This code does not match the behavior of the original function: https://github.com/enarx/tlssock/blob/master/lib/tlssock.c#L234

2019-07-24 14:51 UTC, yingxiongraomingzk commented
Does this looks better now?

2019-07-24 17:40 UTC, npmccallum requested changes

2019-07-24 17:40 UTC, npmccallum commented on src/lib.rs
> +            errno::set_errno(libc::ENOSYS);
Use the `error()` function.

2019-07-24 18:24 UTC, npmccallum requested changes

2019-07-24 18:24 UTC, npmccallum commented on src/lib.rs
> +use libc::{sockaddr, socklen_t};
Don't import the types here. Use `libc::sockaddr` instead below.

2019-07-24 18:28 UTC, npmccallum approved these changes

2019-07-24 18:28 UTC, merged