Implement read() and write() function
enarx/cipherpipe pull request #13
Opened 2019-07-24 19:56 UTC by yingxiongraomingzk

Implement read() and write() function, tls part needs to be
implemented in the future.

2019-07-24 20:15 UTC, yingxiongraomingzk commented
Why the `cargo test --verbose` failed?

2019-07-24 20:19 UTC, npmccallum requested changes

2019-07-24 20:19 UTC, npmccallum commented on src/lib.rs
> +        Some(s) => 0, //TODO: tls_write() implement
Never return success in a stubbed in method. Always return an error.

2019-07-24 20:19 UTC, npmccallum commented on src/lib.rs
> +        Some(s) => 0, //TODO: tls_read() implement
Same as above.

2019-07-24 20:20 UTC, npmccallum commented
> Why the `cargo test --verbose` failed?

Probably because the test process calls `read()` and/or `write()` and you changed the behavior subtly. Alternatively, the `next!()` macro is broken.

2019-07-24 20:44 UTC, yingxiongraomingzk commented
Change the name of the function indeed pass the test. But that's not the thing we expect. Is there any other alternative way we could solve this?

2019-07-24 21:04 UTC, npmccallum commented
You need to debug the problem.

2019-10-22 11:47 UTC, npmccallum commented
Obsoleted by #21.

2019-10-22 11:47 UTC, closed without merging