Add Apache 2.0 license headers to source files
enarx/cipherpipe pull request #18
Opened 2019-09-06 17:28 UTC by mbestavros

Resolves #17.

2019-09-06 18:42 UTC, frozencemetery requested changes
Hmm, this isn't quite how I'd expect to see this.

Typically we'd expect a file - LICENSE or COPYING - at the top level of the repo with the full (Apache, if that's what we're going with) license text in it.  We don't have that already, which is an oversight - I think you should add that as part of this.

Having that file allows us to simplify the header on other files - you can do something like `/* Copyright 2019 the enarx contributors; see COPYING for details */` as a single line file-initial comment and have a much shorter boilerplate.  If a reference would help, you can look at [gssproxy](https://github.com/frozencemetery/gssproxy) for an example of what I mean here.

2019-09-06 18:54 UTC, npmccallum commented
@frozencemetery Sometimes files get copied into other projects without source info. It is my preference to have *both* the license file and a full file header.

2019-09-06 19:02 UTC, mbestavros commented
Updated with separate Apache 2.0 license.

2019-09-06 19:25 UTC, frozencemetery requested changes
Alright, full header it is.

2019-09-06 19:25 UTC, frozencemetery commented on src/header.rs
> +// Copyright 2019 Red Hat
Should be above the `#![allow(dead_code)]` line.

2019-09-06 19:25 UTC, frozencemetery commented on src/lib.rs
> +// Copyright 2019 Red Hat
Same here.

2019-09-09 14:03 UTC, npmccallum approved these changes

2019-09-09 14:03 UTC, merged